### ISSUE TITLE
use pathlib for numsyls function, fix bug with path

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/songdkl#23]
currently the way that numsyls finds .wav files in `path1` causes it to raise an error when the user does not add a final slash, e.g.

```
 poetry run songdkl numsyls ${PCB_SONG_ROOT}/g99o87           
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pimienta/Documents/repos/coding/vocal/songdkl/src/songdkl/__main__.py", line 18, in main
    numsyls(path1=args.path)
  File "/home/pimienta/Documents/repos/coding/vocal/songdkl/src/songdkl/numsyls.py", line 85, in numsyls
    song = impwav(path1 + file)
  File "/home/pimienta/Documents/repos/coding/vocal/songdkl/src/songdkl/audio.py", line 11, in impwav
    wav = wavfile.read(a)
  File "/home/pimienta/anaconda3/envs/vak-env/lib/python3.6/site-packages/scipy/io/wavfile.py", line 544, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/pimienta/Documents/data/doi_10.5061_dryad.8tn4660__v1/pcb_data/song_data/g99o87g99o87.20050523-19.wav'
```

because of the way the functions builds paths to .wav files

Better way would be to just use pathlib and then iterate over `sorted(Path(path1).glob('*.wav'))`

**Comment by NickleDave** [comment]
Fixed by #46
